### PR TITLE
Courses Exploration Visualized

### LINKED ISSUE #74: Add color coding to the course visualizer and graphs
Rohit suggested this and it is a great idea.

Assign each core class a 'color'. Like, 445 red, 449 yellow, 1501 orange, etc. In the course visualization, color code each one to show what the prereqs are.

We can carry this over to the course graphs as well. 

Maybe one way to do this is to have CSS classes like .course-pill-cs0445 { background-color: red; }, and anything that deals with courses can add that id.

We also can create a legend component too as apart of this if we want.

### LINKED ISSUE #79: Make course graphs prettier
They could look a little better

component is in `components/course-graph.js`

styles for it in `components/styles.scss`

### LINKED ISSUE #87: figure out how to replace CMP 401 into CS 401 in a resuable / maintainble way
need like some config to write down if classes get replaced, can auto add redirects and stuff like that

### LINKED ISSUE #99: Related courses in each course page
have a section for related courses.

like compilers, related class would be compilers grad

networks, theres a ton

### LINKED ISSUE #100: Have prereqs be clickable in the course page
like if im 1501 and see the prereqs are cs 447, i want to click that to go to cs 447

### LINKED ISSUE #101: Add right-hand "course preview" from the Courses page to the Course Scheduling guide
title

### PR DESCRIPTION
**Pull request by varughese**
Making it look better. Adding filtering to the course explorer, plus color coding for easy visual grepping.

closes #87 
closes #79 
closes #74 
closes #100 
closes #99
closes #101

Talked to alex about  #56

### CODE REVIEW

**Comment by varughese** [comment]
image

note the 'replaces' field. so annoying :(

```json
    {
      "sci_href": "http://courses.sci.pitt.edu/courses/view/CS-0401",
      "title": "INTERMEDIATE PROGRAMMING",
      "id": "CMP0401",
      "credits": 4,
      "description": "This course is a rigorous introduction to the fundamental concepts and techniques of computer programming using the java programming language.  This is a first course for students who intend to major in computer science.",
      "requirements": " DSAS Quant.-Formal Reason General Ed. Requirement\n",
      "replaces": "CS0401",
      "terms_offered": {
        "SPRING": true,
        "FALL": true,
        "SUMMER": true
      }
    },
```

**Comment by varughese** [comment]
image
clickable prereqs , #100 

need to finish all of the courses in `src/data/requirements.json`

**Comment by varughese** [comment]
image

**Comment by varughese** [comment]
Can you review @Zmwang622   ? https://deploy-preview-98--pittcswiki.netlify.app/ (course explorer, course template, cs 401 -> cmp 401, and scheduling course graph changed)

**Comment by Zmwang622** [comment]
Class Scheduler is extra bolded for some reason:
image

**Comment by Zmwang622** [comment]
Recommend wording changes for this sentence:
image

_to_
Sometimes the hardest part of finding classes is knowing which classes you can actually take. Color coding shows which classes have what requirements based on the a color legend. For example, based on CS 1622 (Compilers)'s dot colors you can tell it has the prerequisites of CS 441 and CS 447.

**Comment by varughese** [comment]
ptal @Zmwang622

**Comment by Zmwang622** [comment]
lgtm

**Pull request merged**
