### PR TITLE
[WIP] Add Basic C++ Getting Started Guide

### PR DESCRIPTION
**Pull request by Richie78321**

### CODE REVIEW

**Comment by zhenyudg** [comment]
One thing that I would point out is that C++20 is quite different from C++98; every new version introduces features that change the best practices of the language (e.g., smart pointers, casts, standard library changes).
Writing "old" C++ code in a modern C++ environment might be frowned upon, say, during an interview.

**Comment by Richie78321** [comment]
@zhenyudg I updated the guide to include info about versions -- how'd I do? Any nits?

**Comment by zhenyudg** [comment]
lgtm

**Review by dylanfeehan — APPROVED** [review]
hello

**Pull request merged**
